version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    groups:
      pip-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      actions-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: ci
