# Changes here will be overwritten by Copier
_commit: "0000000"
_src_path: .
githubActionDescription: DYNAMIC_TOKEN:19bd01a9
githubActionExampleStepName: DYNAMIC_TOKEN:77ad0c5e
githubActionName: DYNAMIC_TOKEN:1fe1a5f3
githubActionNameCamelCase: dynamicToken1fe1a5f3
githubActionNameKebabCase: dynamic-token-1fe1a5f3
githubRepositoryName: dynamic-token-aa9d4c88
githubRepositoryOwner: dynamic-token-0a9c1842
licenseOwner: DYNAMIC_TOKEN:9c3774360
licenseYearStart: 896
