#!/usr/bin/env bash

# Set strict mode for bash
set -euo pipefail

# Bright ANSI color escape sequences.
BRIGHT_MAGENTA=$'\e[1;35m'
BRIGHT_CYAN=$'\e[1;36m'

# Reset all ANSI attributes.
RESET_COLORS=$'\e[0m'

# Named colors
MESSAGE_COLOR="${BRIGHT_CYAN}"
VALUE_COLOR="${BRIGHT_MAGENTA}"

#######################################################################################################################
# Post-commit hook script
#######################################################################################################################

echo "${MESSAGE_COLOR}Restoring dev dependencies to the ${VALUE_COLOR}node_modules/${MESSAGE_COLOR} folder...${RESET_COLORS}"
set -x
npm install
{ set +x; } 2>/dev/null
echo

echo "${MESSAGE_COLOR}Setting the ${VALUE_COLOR}node_modules/.package-lock.json${MESSAGE_COLOR} file worktree tracking skip...${RESET_COLORS}"
set -x
git update-index --skip-worktree node_modules/.package-lock.json
{ set +x; } 2>/dev/null
echo
