#!/usr/bin/env bash

# Set strict mode for bash
set -euo pipefail

# Bright ANSI color escape sequences.
BRIGHT_MAGENTA=$'\e[1;35m'
BRIGHT_CYAN=$'\e[1;36m'

# Reset all ANSI attributes.
RESET_COLORS=$'\e[0m'

# Named colors
MESSAGE_COLOR="${BRIGHT_CYAN}"
VALUE_COLOR="${BRIGHT_MAGENTA}"

#######################################################################################################################
# Pre-commit hook script
#######################################################################################################################

echo "${MESSAGE_COLOR}Running code fixers...${RESET_COLORS}"
set -x
npm run fix
{ set +x; } 2>/dev/null
echo

echo "${MESSAGE_COLOR}Omitting dev dependencies from the local ${VALUE_COLOR}node_modules/${MESSAGE_COLOR} folder...${RESET_COLORS}"
set -x
npm install --omit=dev
{ set +x; } 2>/dev/null
echo

echo "${MESSAGE_COLOR}Restoring the ${VALUE_COLOR}node_modules/.package-lock.json${MESSAGE_COLOR} file worktree tracking status...${RESET_COLORS}"
set -x
git update-index --no-skip-worktree node_modules/.package-lock.json
{ set +x; } 2>/dev/null
echo

echo "${MESSAGE_COLOR}Force adding the ${VALUE_COLOR}node_modules/${MESSAGE_COLOR} folder to the commit...${RESET_COLORS}"
set -x
git add -f node_modules/
{ set +x; } 2>/dev/null
echo
